gText_Birch_Welcome::
	.string "...\p"
	.string "Uh, well welcome then.\p"
	.string "Seems that there are more of\n"
	.string "you to come yet.\p"
	.string "My name is Professor Pando.\p"
	.string "You, my friend, are in Avalon.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This creature is a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "POKéMON are not native to Avalon.\p"
	.string "Though YOU may know of them,\n"
	.string "we were ignorant of their existence.\p"
	.string "These Pokemon only recently appeared\n"
	.string "in Avalon.\p"
	.string "I'm sure you have plenty of questions,\n"
	.string "but for now it must wait.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
